### PR TITLE
fix pulsing

### PR DESCRIPTION
**Pull request by bsuh**
`engine.flood` is used both as a function and a variable. Rename variable to `engine._flood`.

### CODE REVIEW

**Comment by dcerisano** [comment]
Good catch. 
flood() was tacked on as a convenience at the end of the PR for pulse.
Should have caught this in review.

**Comment by mafintosh** [comment]
Could you set the `.pulse` property to `._pulse` as well for consistency?

**Comment by bsuh** [comment]
Done

**Comment by mafintosh** [comment]
Thanks! Released in 0.21.2

**Pull request merged**
